name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with Buildozer Container
        uses: ArtemSbuld/buildozer-action@v2
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: AnyLoad-Final-APK
          path: ${{ steps.buildozer.outputs.filename }}
